INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('American');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('Italian');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('Mexican');
INSERT INTO CATEGORY (CATEGORY_DESCRIPTION) VALUES ('Fast Food');


INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Pint');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Ounce');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (UNIT_OF_MEASURE) VALUES ('Pinch');